ansible_sudo_passwd: "{{ lookup('ansible.builtin.env', 'IDIR_PASSWORD') }}"
default_artifactory_password: "{{ lookup('ansible.builtin.env', 'IDIR_PASSWORD') }}"
default_github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}"
config_branch: "<branch name>"

# Required for 7.6.x
python_executable: /usr/bin/python3.12

# If this is set to true the django migrate will be run.
#perform_migration: True
#migrate_as_superuser: True
#migrations:
#  - ""
#  - "bcrhp 1081_drop_materialized_views"
#  - "models"

# Restart all the s6 services.
restart_s6_services: True

# Reconfigure all the s6 services.
reconfigure_s6_services: True

# Perform a full database refresh at the end of the deployment.
reindex_database: False

db_admin_password_endowment: "<postgres password on endowment>" #ENDOWMENT
db_admin_password_early: "<postgres password on early>" #EARLY

# Working with dev release so the version number doesn't change. Need to force reinstall
force_core_pip_install: True
core_repo_tag: "stable/7.6.4_bcgov_11578_11716_11729_11723"
common_repo_tag: "bugfix/1223_fix_missing_popup_links"
